---
title: "Untitled"
author: "GSTAT"
date: "December 18, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div dir="rtl">

# שאלות 1


1.1. כתבו פונקציה המדפיסה את המילים שמזינים לה בתור input


1.2. כתבו פונקציה המקבלת כערך עמודה של dplyr ומחזירה חישוב של העמודה בריבוע - בדקו אותו על santander_sample ועמודה renta 


1.3.  השתמשו באחד הפקודות שלמדנו כדי לקבל את ממוצע הערכים מ 1 עד 100. ובאותו שורת קוד גם את ממוצע הערכים מ 50 עד 90. מה היה יוצא אם משתמשים ב map לעומת map_dbl?


1.4.  השתמשו באחד הפקודות שלמדנו כדי לייצר רשימה (list ) עם שתי עמודות  ו 1000 שורות. 
בעמודה אחת וקטור של מדגם מקרי מההתפלגות הנורמלית עם ממוצע של 0 ובעמודה השניה מדגם מקרי מהתפלגות נורמלית עם ממוצע של 50.



1.5. הציגו היסטוגרמות של מה שייצרתם בפקודה הקודמת בעזרת walk ובעזרת פקודת הבסיס hist.

_________________


# שאלות 2

2.1. בעזרת הפקודה cut כתבו פונקציה המקבלת וקטור וחותכת אותו ב 3 מקומות (0, 1000, 20000)
	בדקו אותו על santander_sample ועמודה renta.

	
2.2. שדרגו את הפונקציה שיצרתם כך שתחזיר פונקציה החותכת משתנה כלשהו במקומות שמזינים לה - 
  קראו לפונקציה הזאת grp_format

  
2.3. השתמשו בפונקציה שיצרתם בתוך שאילתא של dplyr המחזירה את הספירה של התצפיות לפי חיתוכים שונים של המשתנה renta
 שלכם ואת הממוצע של ind_cc בכל חיתוך.
 תחליטו על 3 אופציות של חיתוכים .
 רמז: לפני השאילתא תשמרו את 3 החיתוכים האפשריים כפונקציות - שאחר כך תשתמשו בהם בשאילתות נפרדות...
 
_________________
 
 
# שאלות 3

3.1.  שמרו ב list שתי אפשרויות לרגרסיה  על renta. אחד עם המשתנים המסבירים age sexo  segmento ואחד רק עם המשתנים
age ו sexo.

3.2. הריצו בעזרת אחד הפקודות שלמדנו היום את שתי האופציות כרגרסיה ליניארית בבת אחת. שמרו את התוצאות בתור list.

3.3. תציגו את כל אחד מתוצאות הרגרסיה בנפרד.

3.4. תנסו להוציא רק את ה R בריבוע של שתי הרגרסיות שהרצתם. 



____________


</div>

