---
title: "tutorial_2_questions"
author: "GSTAT"
date: "November 30, 2016"
output: 
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
____________________________________________     

<div dir ="rtl">
## תרגיל 1 -  שאלות  בשאילתות בסיסיות

1. חישבו סטטיסטיקה תאורית (סכום, ממוצע, סטיית תקן, וכו) על המשתנה renta

2. חזרו על שאלה 1 לפי קבוצת במשתנה sexo

3. חזרו על שאלה 2 כאשר אתם מסננים renta שהם פחות מ 100

4. חזרו על שאלה 2 כאשר אתם מציגים רק קבוצות שיש בהן לפחות 100 תצפיות

5. יצרו טבלה חדשה בשם santander_short המכילה את העמודות:  ind_cc, ncodpers, age, sexo, renta, antiguedad  ו - nomprov . 
	אבל, בטבלה החדשה תמירו את השם antiguedad לשם vetek .

6. בטבלה שיצרתם, תשנו את העמודה vetek שיהיה מחושבת בשנים ולא בחודשים

7. תייצרו משתנה gil_vetek המקבל את הערך:
	* 1 - אם הלקוח מתחת לגיל 30 והותק שלו פחות מ 3
	* 2 - אם הלקוח מתחת לגיל 30 והותק שלו יותר מ 3
	* 3 - אם הלקוח מעל גיל 30 עם ותק מתחת ל 5
	* 4 - אחרת  
	  
	(ניתן להשתמש בפקודה ifelse מספר פעמים)  
	
	הציגו ספירה של המשתנה שיצרתם
	
8. מה הערך הממוצע של ind_cc עבור nomprov  במחוז BARCELONA לפי gil_vetek

9. תייצרו טבלה בשם prov_stats עם: ממוצע  של המשתנה ind_cc לפי המשתנה nom_prov ממויין לפי מספר התצפיות במחוז מגדול לקטן

10. איזה nomprov נמצא במקום ה 18 בטבלה שיצרתם


____________________________________________


## תרגיל 2 -  שאלות  בשאילתות מורכבות יותר

1. כתבו שאילתא לבדוק אם יש כפילויות  , של שילוב המשתנים fecha_dato יחד עם ncodpers, בקובץ Santander_sample

2. חישבו את הממוצע של המשתנים הנומריים בטבלה santander_short בעזרת כל אחד מפקודות ה summarise המיוחדות (at,all,if).  

רמז: חפשו עזרה על הפקודה `is.numeric`
  
3. בטבלה prov_stats, הוסיפו עמודה של אחוז , ואחוז מצטבר - מהגדול לקטן - תתנו להם את השמות: nomrprov_percent ו- nomprov_cumpercent (בנקודות עשרוניות).
 כמו כן, הוסיפו עוד עמודה המדרגת את המחוזות לפי ממוצע ind_cc שבטבלה, מהגדול לקטן,  תקראו לו rank_cc

4. בעזרת `mutate_at`  המירו את השדות של האחוזים שהוספתם בסעיף הקודם לאחוזים (להכפיל ב 100) . תנסו לעשות את זה בעזרת אחד מה `select_helpers` . תחפשו בעזרה...

5. כתבו שאילתא שתשלוף את השורות עם דירוג rank_cc הגבוה ביותר והנמוך ביותר

6. תוסיפו לטבלה santander_short , עמודה המכילה את ה renta  הממוצעת לפי המשתנה nomprov , תקראו לו mean_renta	

7. מבלי להוסיף עוד עמודה, תעדכנו את הטבלה כך שיכיל רק את התצפיות בהן ערך renta מעל לערך renta החציוני בכל קבוצה של nomprov

8. תציגו  את 7  השורות בהן ערך ה renta הגבוה ביותר בטלה prov_stats

9. תייצרו טבלה חדשה בשם santander_short2 על ידי חיבור של הטבלה prov_stats ל  santander_short לפי מחוז 

10. סננו את הטבלה prov_stats שיכיל רק מחוזות המהוות יותר  1% מהאוכלוסיה - ותיצרו טבלה חדשה בשם santander_short2 על ידי חיבור של הטבלה המסוננת ל santander_short בעזרת semi_join על מנת לסנן את המחוזות האלה מהטבלה 

____________________________________________

## תרגיל 3 -  שאלות  בשינוי צורת טבלה

* בשביל להדגיש את ההבדלים בין החבילות, תנסו את התרגילים למעט 3, ו - 4 בעזרת שתי החבילות שלמדנו

1. קבצו את הקובץ prov_stats שיכיל רק 3 עמודות: nomprov, variable ו - variable_value

2. החזירו את הקובץprov_stats לצורתה המקורית

3. בטבלה santander_short תחברו את העמודות age ו sexo לתוך עמודה age_sex המופרד בסימן "_"

4. תפרידו בחזרה בין העמודות - תקפידו ש age יחזור להיות integer  . ראו עזרה אם צריך...

5. תייצרו טבלה santander_melt המבוסס על הטבלה santander_short שבמקום המשתנים renta ו mean_renta יהיה עמודה אחת var_names המכיל את שמות העמודות הללו ועוד עמודה var_values  המכיל את הערכים של העמודות הללו, וששאר העמודות ישארו כמו שהיו  

  תקראו את העזרה אם צריך...

6. תחזירו את הטבלה בחזרה לצורתה המקורית ותקראו לטבלה החדשה santander_cast  

  תקראו את העזרה אם צריך...

7. יצרו מהטבלה santander_melt את הטבלה santander_cast שיכיל את הערכים הממוצעים של renta ו mean_renta לפי nomprov  ו sexo

8. איזה תרגילים לא הצלחתם לעשות בפקודה אחת בעזרת `tidyr` ?

______________________    

</div>